# Human readable name of this type
name: Profiles

# Lowercase, underscored handle used to access this type
slug: profiles

# Explanatory text displayed in the back-office
description: A description of the content type for the editors

# Slug of field used to identify entries by default, such as the title
label_field_name: name

# Valid values: manually, created_at, updated_at, or the slug of any field
order_by: name

# Valid values: asc (ascending) and desc (descending). Set to asc by default.
# order_direction: asc

# Specify a field slug to group entries by that field in the back-office.
# group_by: <your field>

# Activate public 'create' API (e.g for a contact form)
# public_submission_enabled: false

# Array of emails to be notified of new entries made with the public API
# public_submission_accounts: ['john@example.com']

# A list describing each field
fields:
- name: # The lowercase, underscored name of the field
    label: Name # Human readable name of the field
    type: string
    required: true
    localized: false

- description: # The lowercase, underscored name of the field
    label: Description # Human readable name of the field
    type: text
    required: false
    hint: Describe this profile
    localized: false
    text_formatting: html # html (uses rich text editor) or text (uses plain text editor)

- category:
    label: Category
    type: belongs_to
    class_name: categories
    # required: true
    hint: Select category

- tag1: # The lowercase, underscored name of the field
    label: Tag1 # Human readable name of the field
    type: tags
    required: false
    hint: Tag this profile. Use commas to separate tags.
    localized: false

- tag2: # The lowercase, underscored name of the field
    label: Tag2 # Human readable name of the field
    type: tags
    required: false
    hint: Tag this profile. Use commas to separate tags.
    localized: false

- tag3: # The lowercase, underscored name of the field
    label: Tag3 # Human readable name of the field
    type: tags
    required: false
    hint: Tag this profile. Use commas to separate tags.
    localized: false

- address: # The lowercase, underscored name of the field
    label: Address # Human readable name of the field
    type: text
    required: false
    localized: false

- zip: # The lowercase, underscored name of the field
    label: Zip # Human readable name of the field
    type: text
    required: false
    localized: false

- website: # The lowercase, underscored name of the field
    label: Website # Human readable name of the field
    type: text
    required: false
    localized: false

- email: # The lowercase, underscored name of the field
    label: Email # Human readable name of the field
    type: text
    required: false
    localized: false

- logo_image: # The lowercase, underscored name of the field
    label: Logo image # Human readable name of the field
    type: file
    required: false
    localized: false

- lat: # The lowercase, underscored name of the field
    label: Latitude
    type: float
    required: false
    localized: false

- lon: # The lowercase, underscored name of the field
    label: Longitude
    type: float
    required: false
    localized: false
